### ISSUE TITLE
Formulate Button

### ISSUE THREAD

**Issue by Om-Govindani** [Om-Govindani/GymGuy#1]
Formulate Button Needs to be Clicked Twice. i.e., on clicking second time only the page scrolls to the workout section

**Comment by prateekThakur84** [comment]
their is a mistake in exerciseCard component, at line no 22 ....
Each element created in a loop should have a unique key prop...

corrected code :- **<div className="flex flex-col bg-slate-950 rounded gap-2">
        {exercise.description.split("___").map((val, index) => (
          <div className="text-sm" key={index}>
            {val}
          </div>
        ))}
      </div>**

**Comment by Om-Govindani** [comment]
> their is a mistake in exerciseCard component, at line no 22 .... Each element created in a loop should have a unique key prop...
> 
> corrected code :-
> 
> ** {exercise.description.split("___").map((val, index) => ( {val} ))} **

Thanks @prateekThakur84 Will Look After this

**Comment by Om-Govindani** [comment]
> Formulate Button Needs to be Clicked Twice. i.e., on clicking second time only the page scrolls to the workout section

Adding a useEffect() after the updateWorkout function in src/App.jsx Solved the issue related to The Formulate Button

useEffect(() => {
    if (workout) {
      window.location.href = '#workout'
    }
  }, [workout]);
